---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-go
  labels:
    role: guestbook-go
spec:
  selector:
    role: guestbook-go
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000
  type: NodePort

---
apiVersion: v1
kind: Pod
metadata:
  name: guestbook-go
  labels:
    role: guest-book
    version: v1
spec:
  containers:
    - name: app
      image: guest-book:tag